const countries = [
  {
    country: 'Belarus',
    cities: [
      'Borisov',
      'Dzerzhinsk',
      'Mar’ina Gorka',
      'Minsk',
      'Molodechno',
      'Soligorsk',
      'Slutsk',
      'Stolbtsy',
      'Vileyka',
      'Zhodino',
    ],
  },
  {
    country: 'Czech Republic',
    cities: [
      'Brno',
      'České Budějovice',
      'Hradec Králové',
      'Liberec',
      'Olomuc',
      'Ostrava',
      'Pardubice',
      'Prague',
      'Plzeň',
      'Ústí nad Labem',
    ],
  },
  {
    country: 'Latvia',
    cities: [
      'Daugavpils',
      'Jēkabpils',
      'Jelgava',
      'Jūrmala',
      'Liepāja',
      'Ogre',
      'Rēzekne',
      'Riga',
      'Valmiera',
      'Ventspils',
    ],
  },
  {
    country: 'Republic of Moldova',
    cities: [
      'Bălți',
      'Bender (Tighina)',
      'Cahul',
      'Chișinău',
      'Comrat',
      'Orhei',
      'Rîbnița',
      'Soroca',
      'Tiraspol',
      'Ungheni',
    ],
  },
  {
    country: 'Romania',
    cities: [
      'Brașov',
      'Bucharest',
      'Cluj-Napoca',
      'Constanța',
      'Craiova',
      'Galați',
      'Iași',
      'Oradea',
      'Timișoara',
      'Ploiești',
    ],
  },
  {
    country: 'Russian Federation',
    cities: [
      'Chelyabinks',
      'Kazan',
      'Moscow',
      'Nizhny Novgorod',
      'Novosibirsk',
      'Omsk',
      'Rostov-on-Don',
      'Saint Petersburg',
      'Samara',
      'Yekaterinburg',
    ],
  },
  {
    country: 'Ukraine',
    cities: [
      'Dnipro',
      'Donetsk',
      'Kharkiv',
      'Kryvyi Rih',
      'Kyiv',
      'Lviv',
      'Mariupol',
      'Mykolaiv',
      'Odesa',
      'Zaporizhzhia',
    ],
  },
];

export { countries };
